project:
  type: website
  render:
    - index.qmd
    - vignettes/2025_05_02_output_zonation.qmd
    - vignettes/input_sdm.qmd
    - vignettes/input_habitats.qmd
    - vignettes/threats_development.qmd
    - vignettes/threats_fire.qmd
    - vignettes/threats_invasive_species.qmd
    - vignettes/threats_logging.qmd
    - vignettes/species_richness.qmd
    - vignettes/tree_density_from_lidar.qmd
    - vignettes/inaturalist.qmd
    - vignettes/protected_areas.qmd
    - vignettes/downloads.qmd

execute:
  freeze: true

website:
  title: "Bowen Island Biodiversity Plan"
  repo-url: https://github.com/Palen-Lab/bowen.biodiversity.webapp
  repo-actions: [edit, source, issue]
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - vignettes/input_sdm.qmd
      - vignettes/input_habitats.qmd
      - vignettes/2025_05_02_output_zonation.qmd
      - section: "Threats"
        contents:
          - vignettes/threats_development.qmd
          - vignettes/threats_fire.qmd
          - vignettes/threats_invasive_species.qmd
          - vignettes/threats_logging.qmd
      - section: "Action"
        contents:
          - vignettes/protected_areas.qmd
      - section: "Supplementary"
        contents:
          - vignettes/species_richness.qmd
          - vignettes/tree_density_from_lidar.qmd
          - vignettes/inaturalist.qmd
      - vignettes/downloads.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
