project:
  type: website
  render:
    - index.qmd
    - vignettes/output_zonation_01_02_2025.qmd
    - vignettes/output_zonation_17_04_2025.qmd
    - vignettes/output_zonation_24_04_2025.qmd
    - vignettes/output_zonation_02_05_2025.qmd
    - vignettes/input_sdm.qmd
    - vignettes/input_habitats.qmd
    - vignettes/threats_development.qmd
    - vignettes/threats_fire.qmd
    - vignettes/threats_invasive_species.qmd
    - vignettes/threats_logging.qmd
    - vignettes/species_richness.qmd
    - vignettes/tree_density_from_lidar.qmd
    - vignettes/inaturalist.qmd

execute:
  freeze: auto

website:
  title: "Bowen Island Biodiversity Plan"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "Conservation Layers"
        contents:
          - vignettes/input_sdm.qmd
          - vignettes/input_habitats.qmd
      - section: "Zonation"
        contents:
          - vignettes/output_zonation_01_02_2025.qmd
          - vignettes/output_zonation_17_04_2025.qmd
          - vignettes/output_zonation_24_04_2025.qmd
          - vignettes/output_zonation_02_05_2025.qmd
      - section: "Threats"
        contents:
          - vignettes/threats_development.qmd
          - vignettes/threats_fire.qmd
          - vignettes/threats_invasive_species.qmd
          - vignettes/threats_logging.qmd
      - section: "Supplementary"
        contents:
          - vignettes/species_richness.qmd
          - vignettes/tree_density_from_lidar.qmd
          - vignettes/inaturalist.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
